In [15]:
import pandas as pd
import numpy as np

In [16]:
train = pd.read_csv('../data/raw/test.csv')

In [17]:
train.shape

(254655, 20)

In [18]:
train.info()
train.describe().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254655 entries, 0 to 254654
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                254655 non-null  int64
 1   gender            254655 non-null  object
 2   SeniorCitizen     254655 non-null  int64
 3   Partner           254655 non-null  object
 4   Dependents        254655 non-null  object
 5   tenure            254655 non-null  int64
 6   PhoneService      254655 non-null  object
 7   MultipleLines     254655 non-null  object
 8   InternetService   254655 non-null  object
 9   OnlineSecurity    254655 non-null  object
 10  OnlineBackup      254655 non-null  object
 11  DeviceProtection  254655 non-null  object
 12  TechSupport       254655 non-null  object
 13  StreamingTV       254655 non-null  object
 14  StreamingMovies   254655 non-null  object
 15  Contract          254655 non-null  object
 16  PaperlessBilling  254655 non-null  object
 17  PaymentMethod     254655 non-null  object
 18  MonthlyCharges    254655 non-null  float64
 19  TotalCharges      254655 non-null  float64
dtypes: float64(2), int64(3), object(15)
memory usage: 38.9+ MB

,count,mean,std,min,25%,50%,75%,max
id,254655.0,721521.000000,73512.710738,594194.0,657857.500,721521.00,785184.5,848848.00
SeniorCitizen,254655.0,0.113620,0.317350,0.0,0.000,0.00,0.0,1.00
tenure,254655.0,37.279716,24.777625,1.0,13.000,36.00,62.0,72.00
MonthlyCharges,254655.0,66.130803,31.104139,18.3,30.150,74.35,91.1,118.75
TotalCharges,254655.0,2544.617351,2348.124379,18.8,677.625,1468.75,4317.3,8684.80

In [19]:
train.head(10)

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,594194,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.55,8061.50
1,594195,Female,0,Yes,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.80,1336.50
2,594196,Male,0,No,No,12,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.55,633.55
3,594197,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.10,6457.15
4,594198,Female,0,No,No,15,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,90.35,1233.65
5,594199,Male,0,No,No,24,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Credit card (automatic),69.95,1406.20
6,594200,Female,0,No,No,1,Yes,No,Fiber optic,Yes,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,78.60,78.60
7,594201,Female,0,No,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,No,Two year,Yes,Bank transfer (automatic),60.35,3825.20
8,594202,Female,0,Yes,No,55,Yes,Yes,Fiber optic,No,No,No,No,No,No,One year,No,Credit card (automatic),75.45,4459.15
9,594203,Female,0,No,No,50,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Month-to-month,Yes,Electronic check,89.85,4533.90

In [20]:
train.isnull().sum()

id                  0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

In [21]:
train[["gender", "Dependents", "InternetService", "PaymentMethod"]] = train[["gender", "Dependents", "InternetService", "PaymentMethod"]].astype("string")
train[["Partner", "PhoneService", "MultipleLines", "OnlineSecurity", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling"]] = train[["Partner", "PhoneService", "MultipleLines", "OnlineSecurity", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling"]].astype("category")

In [22]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254655 entries, 0 to 254654
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                254655 non-null  int64
 1   gender            254655 non-null  string
 2   SeniorCitizen     254655 non-null  int64
 3   Partner           254655 non-null  category
 4   Dependents        254655 non-null  string
 5   tenure            254655 non-null  int64
 6   PhoneService      254655 non-null  category
 7   MultipleLines     254655 non-null  category
 8   InternetService   254655 non-null  string
 9   OnlineSecurity    254655 non-null  category
 10  OnlineBackup      254655 non-null  object
 11  DeviceProtection  254655 non-null  category
 12  TechSupport       254655 non-null  category
 13  StreamingTV       254655 non-null  category
 14  StreamingMovies   254655 non-null  category
 15  Contract          254655 non-null  category
 16  PaperlessBilling  254655 non-null  category
 17  PaymentMethod     254655 non-null  string
 18  MonthlyCharges    254655 non-null  float64
 19  TotalCharges      254655 non-null  float64
dtypes: category(10), float64(2), int64(3), object(1), string(4)
memory usage: 21.9+ MB

In [23]:
train.to_csv('../data/raw/test.csv', index=False)